from dataclasses import dataclass
from enum import Enum
from typing import List

class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    NONE = "NONE"

@dataclass(frozen=True)
class SignalCandidate:
    """
    Immutable candidate signal generated by a specific strategy.
    Acts as the standard data contract for the Signal Engine 
    and downstream AI/Decision layers.
    """
    signal_type: SignalType
    entry: float
    stop_loss: float
    take_profit: float
    strategy_name: str
    confidence: float
    reasons: List[str]
