"""
AI Layer — Research Model (Phase 66.8: AI Research Intelligence
Foundation, TASK 2). Final phase of the `66.x` AI Trading Intelligence
sub-sequence.

`ResearchRecord`/`ResearchStatus`/`ResearchPriority`/`ResearchCategory`
follow the same Article 3 resolution `ai/trade_journal/models.py`,
`ai/learning/models.py`, `ai/coaching/models.py`, `ai/performance/models.py`,
`ai/strategy/models.py`, and `ai/portfolio/models.py` all already
established: every field is a primitive (`str`/`int`) or an enum
defined in this same file -- never a `decision_layer.decision_engine.models.TradeDecision`,
`risk_layer.risk_engine.risk_manager.RiskResult`, or any other Trading Core object
reference. `ai/research/` never imports `decision/`, `risk/`,
`execution/`, `strategies/`, `signals/`, `context/`, `monitoring/`,
`telegram/`, `database/`, `voice/`, `assistant/`, `core.`, or
`ai.memory`.

**No naming collision** (documented, see `docs/PHASE66_8_AUDIT.md`'s
"Question 1"): a repository-wide search found no pre-existing
`Research`-shaped model anywhere, including no pre-existing top-level
`research/` package (confirmed absent, not merely import-forbidden).
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional
from uuid import uuid4


class ResearchStatus(Enum):
    """TASK 2's own exact vocabulary -- caller-supplied, never inferred by this package."""

    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class ResearchPriority(Enum):
    """TASK 2's own exact vocabulary -- a caller-supplied qualitative label, never computed by this package (Rule 5: CRUD only)."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ResearchCategory(Enum):
    """TASK 2's own exact vocabulary -- caller-supplied or, for the three sibling-Foundation adapters, a structural constant of that adapter (see docs/PHASE66_8_AUDIT.md's 'Question 6'), never inferred from record content."""

    MARKET = "MARKET"
    STRATEGY = "STRATEGY"
    PERFORMANCE = "PERFORMANCE"
    PORTFOLIO = "PORTFOLIO"
    LEARNING = "LEARNING"
    GENERAL = "GENERAL"


@dataclass(frozen=True)
class ResearchRecord:
    """
    TASK 2's own exact field list: `research_id`, `title`, `category`,
    `priority`, `status`, `summary`, `source_count`, `notes`,
    `created_at`.

    research_id: this record's own generated identity
        (`generate_research_id()`).
    title: free-text display title -- caller-supplied, never inferred.
    category: `ResearchCategory` -- caller-supplied classification.
    priority: `ResearchPriority`, defaults to `MEDIUM` -- mirrors
        `ai.coaching.models.CoachingRecommendation.priority`'s own
        default precedent.
    status: `ResearchStatus`, mutated only via `ResearchRuntime.archive()`/
        `update()`. Defaults to `ACTIVE` -- a research item being
        tracked by this Foundation is, by definition, already in use,
        mirroring `ai.portfolio.models.PortfolioRecord.status`'s own
        `ACTIVE` default precedent.
    summary: a short free-text summary -- always caller-supplied, never
        generated by this package (Rule 4: no LLM/reasoning).
    source_count: a plain caller-supplied count of how many sources
        this research item cites -- this module never computes it
        itself (see `docs/PHASE66_8_AUDIT.md`'s "Question 6": no
        sibling-Foundation adapter aggregates it, since none of
        `PerformanceRecord`/`StrategyRecord`/`PortfolioRecord` carries
        an equivalent "sources" concept).
    notes: a short free-text note.
    created_at: ISO-8601 timestamp string, stamped by
        `ResearchRuntime.create()`.
    """

    research_id: str
    title: str
    category: ResearchCategory
    priority: ResearchPriority = ResearchPriority.MEDIUM
    status: ResearchStatus = ResearchStatus.ACTIVE
    summary: Optional[str] = None
    source_count: int = 0
    notes: Optional[str] = None
    created_at: str = ""


def generate_research_id() -> str:
    """Same stateless uuid4 convention as every other generate_X_id() in this codebase (e.g. ai.portfolio.models.generate_portfolio_id())."""
    return str(uuid4())
