"""context_layer/context_engine/context_orchestrator -- canonical module package (GoldBot Engineering Law GEL-001, Strict).

Implementation in `context_orchestrator.py`; this `__init__` re-exports the public surface
so every established import path stays stable. Generated 2026-08-04. No behaviour
changed; the module code was moved intact from the former flat `context_orchestrator.py`.
"""
from context_layer.context_engine.context_orchestrator.context_orchestrator import (
    dataclass,
    List,
    Optional,
    Sequence,
    TYPE_CHECKING,
    Candle,
    ContextConfig,
    detect_swing_points,
    classify_structure,
    SwingPoint,
    StructurePoint,
    detect_bos,
    BosEvent,
    detect_choch,
    ChochEvent,
    detect_equal_levels,
    detect_sweeps,
    LiquidityZone,
    LiquiditySweepEvent,
    detect_order_blocks,
    OrderBlock,
    detect_fvg,
    FairValueGap,
    detect_amd_events,
    AmdEvent,
    detect_wyckoff_events,
    WyckoffEvent,
    detect_session_events,
    SessionEvent,
    compute_market_regime,
    MarketRegimeResult,
    setup_logger,
    logger,
    ContextSnapshot,
    ContextEngine,
    build_context_snapshot,
)

__all__ = [
    "dataclass",
    "List",
    "Optional",
    "Sequence",
    "TYPE_CHECKING",
    "Candle",
    "ContextConfig",
    "detect_swing_points",
    "classify_structure",
    "SwingPoint",
    "StructurePoint",
    "detect_bos",
    "BosEvent",
    "detect_choch",
    "ChochEvent",
    "detect_equal_levels",
    "detect_sweeps",
    "LiquidityZone",
    "LiquiditySweepEvent",
    "detect_order_blocks",
    "OrderBlock",
    "detect_fvg",
    "FairValueGap",
    "detect_amd_events",
    "AmdEvent",
    "detect_wyckoff_events",
    "WyckoffEvent",
    "detect_session_events",
    "SessionEvent",
    "compute_market_regime",
    "MarketRegimeResult",
    "setup_logger",
    "logger",
    "ContextSnapshot",
    "ContextEngine",
    "build_context_snapshot",
]
